name: Test website for js vulnerabilities

on:
  schedule:
    - cron: "0 0 * * 7"
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Is Website vulnerable
        uses: lirantal/is-website-vulnerable@1.15.10
        with:
          scan-url: "https://shiftgeist.com/"
