name: CI

on: [push, pull_request]

env:
  node_version: 14

jobs:
  ci:
    name: CI with Node ${{ env.node_version }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.3
      - name: Use Node ${{ matrix.node_version }}
        uses: actions/setup-node@v2.1.5
        with:
          node_version: ${{ matrix.node_version }}
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build
