name: CI

on: [push, pull_request]

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.3
      - name: Setup node
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build
